# Generated by Django 4.0.4 on 2022-05-05 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='supportContact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_contracts', to='core.client'),
        ),
        migrations.AddField(
            model_name='contract',
            name='salesContact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='salesContact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
