# Generated by Django 4.0.4 on 2022-05-12 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='salesContact',
            field=models.ForeignKey(limit_choices_to={'Sale user': True}, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
